# The Site Configuration
# Documentation: https://chirpy.cotes.page/posts/getting-started/

# Site settings
title: DS's Blog
tagline: 技術筆記與生活分享
description: >-
  分享程式開發、技術心得，以及生活點滴的個人部落格。
url: "https://zekkar.github.io"
github_username: Zekkar
# twitter_username: twitter_handle
social:
  name: DS
  email: drake666lord@gmail.com
  links:
    - https://github.com/Zekkar
    # - https://twitter.com/username
    # - https://www.linkedin.com/in/username

author: DS
timezone: Asia/Taipei

# Theme settings
theme: jekyll-theme-chirpy

# Language
lang: zh-TW

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Assets
avatar: /assets/images/profile.jpg # 您稍後可以上傳一張頭像到此路徑
# banner:
#   image: /assets/img/bg.jpg

# Sidebar
sidebar:
  display_author: true
  
# Search
search:
  provider: google
  google:
    search_engine_id: # 您可以在這裡設定 Google Custom Search Engine ID (選擇性)

# Analytics
google_analytics:
  id: "G-H7VC2XRWBJ" # 您的 GA4 ID
  pv:
    proxy_url:
    cache_path:

# Comments
disqus:
  shortname: # 填入您的 Disqus shortname
# utterances:
#   repo: # <username>/<repo>
# giscus:
#   repo: # <username>/<repo>

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /posts/:title/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-theme-chirpy

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .github
  - .gitignore